spring:  
  datasource:
      type : com.alibaba.druid.pool.DruidDataSource
      name : writeDruidDataSource
      driver-class-name : com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://192.168.1.251:3306/db_mafruits?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
      username : developer
      password : 123456
server:
  port: 8081
  servlet:
    context-path: /demo
logging:
  level:
    com.example: debug